name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Debigging gh action
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: tartavull
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-shell ./nix/shell.nix --run "cd .. && pre-commit run --all"
      - run: nix-shell ./nix/shell.nix --run "cd .. && pytest"
