name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Disk Space Before
        run: df -h

      - name: Remove Directories and Check Disk Space After
        run: |
          sudo rm -rf /usr/share/dotnet \
          && sudo rm -rf /opt/ghc \
          && sudo rm -rf "/usr/local/share/boost" \
          && sudo rm -rf "$AGENT_TOOLSDIRECTORY" \
          && df -h

      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

      - name: Cache build on cachix
        uses: cachix/cachix-action@v11
        with:
          name: cuda-maintainers
      - name: Cache build on cachix
        uses: cachix/cachix-action@v11
        with:
          name: tartavull
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Shell
        run: nix develop --command bash -c "echo Build finished"
      - name: Run pre-commit
        run: nix develop --command bash -c "pre-commit run --all"
      - name: Run pytest
        run: nix develop --command bash -c "pytest"
