name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - name: Cache build on cachix
        uses: cachix/cachix-action@v11
        with:
          name: tartavull
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run pre-commit tests
        run: nix develop --command bash -c "pre-commit run --all"
      - name: Run pytest
        run: nix develop --command bash -c "pytest"
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Build gcp image
        run: nix build .#gcp && mkdir images && cp ./result/*.raw.tar.gz ./images/gcp
      - name: Build aws image
        run: nix build .#aws && cp ./result/*.vhd ./images/aws
      - name: Upload images
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: "./images"
          destination: "openmind-vision/${{ steps.branch-name.outputs.current_branch }}"
          parent: false
