name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - name: Cache build on cachix
        uses: cachix/cachix-action@v11
        with:
          name: tartavull
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run pre-commit tests
        run: nix develop --command bash -c "pre-commit run --all"
      - name: Run pytest
        run: nix develop --command bash -c "pytest"
